apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-workshop-deployment
  labels:
    app: gitops-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-workshop
  template:
    metadata:
      labels:
        app: gitops-workshop
    spec:
      containers:
      - name: gitops-workshop-website
        image: https://docker.io/berneg/gitops-workshop
        ports:
        - containerPort: 80